DCOMM-264 Add step to teat failure. (to be removed)

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -83,6 +83,14 @@ jobs:
           labels: ${{ steps.metadata.outputs.labels }}
           push: true
 
+      # --- TEMPORARY: Force failure to test email/Slack notifications ---
+      - name: Force Failure (test only)
+        run: |
+          echo "Intentionally failing this workflow for notification testing"
+          exit 1
+      # -------------------------------------------------------------------
+
+
       - name: Messaging for Build
         if: ${{ always() }}
         run: |
